To finish installation of flocon, add the following line to your
/etc/pacman.d/mirrolist:

Server = http://localhost:19433/$repo/os/$arch

Additionally, if you get sick of 404s, you can duplicate your second server and
add the comment "# flocon: " in from of the line, so that flocon will fallback
on it, instead of issuing a 404. Your mirrorlist would then look like this:

Server = http://localhost:19433/$repo/os/$arch
# flocon: Server = ...
Server = ...
